config/routes.rb
Lassie::Application.routes.draw do

  # Root:
  root 'projects#index'

  # Login / Logout:
  get '/login' => 'sessions#new', as: 'signin'
  delete '/logout' => 'sessions#destroy', as: 'signout'

  # Sessions / Users / Behaviors
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  
  # Project resources:
  resources :projects do
    resources :actors
    resources :assets
    resources :behavior_types
    resources :inventory_combos
    resources :inventory_items
    resources :inventory_lists
    resources :scenes

    # Landing pages:
    get '/setup' => 'projects#setup'
    get '/inventory' => 'projects#inventory'
  end

  # JSON API methods
  resources :behaviors, except: [:new, :edit]
  resources :scene_layers, except: [:new, :edit]
  resources :scene_grids, except: [:new, :edit]
  resources :scene_matrices, except: [:new, :edit]

end

app/models/inventory_item.rb
class InventoryItem < ActiveRecord::Base
  belongs_to :project
  has_and_belongs_to_many :inventory_combos
  has_and_belongs_to_many :inventory_lists
  has_many :behaviors, as: :behavioral, dependent: :destroy
end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  layout 'project'

  before_action :require_signin
  before_action :find_parent_project
  before_action :find_inventory_item, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
    @item = InventoryItem.new
  end

  def create
    @item = @project.inventory_items.create(inventory_item_params)
    redirect_to project_inventory_items_path(@project)
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def find_inventory_item
    @item = InventoryItem.find(params[:id])
  end

  def inventory_item_params
    params.require(:inventory_item).permit(:name, :slug)
  end
end

app/views/inventory_items/_form.html.erb
<%= form_for [@project, @item] do |f| %>
<ul>
  <li>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </li>
  <li>
  <%= f.label :slug %>
  <%= f.text_field :slug %>
  </li>
</ul>
<%= f.submit 'Submit', id: 'submit' %>
<%= link_to 'Cancel', project_inventory_items_path(@project) %>
<% end %>

app/views/inventory_items/edit.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Inventory', project_inventory_path(@project) %></li>
  <li><%= link_to 'Items', project_inventory_items_path(@project) %></li>
  <li>Edit <%= @item.slug %></li>
<% end %>

<% content_for :header do %>
  <h1>Edit <%= @item.name %></h1>
<% end %>

<% content_for :content do %>
  <%= render partial: 'form' %>
<% end %>

app/views/inventory_items/index.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Inventory', project_inventory_path(@project) %></li>
  <li>Items</li>
<% end %>

<% content_for :header do %>
  <h1>Inventory Items</h1>
  <%= link_to '+', new_project_inventory_item_path(@project) %>
<% end %>

<% content_for :content do %>
  <ul>
    <% @project.inventory_items.each do |item| %>
    <li>
      <%= link_to item.name, project_inventory_item_path(@project, item) %>
      <%= link_to 'Edit', edit_project_inventory_item_path(@project, item) %>
      <%= link_to 'Delete', project_inventory_item_path(@project, item), method: 'delete' %>
    </li>
    <% end %>
  </ul>
<% end %>

app/views/inventory_items/new.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Inventory', project_inventory_path(@project) %></li>
  <li><%= link_to 'Items', project_inventory_items_path(@project) %></li>
  <li>New Item</li>
<% end %>

<% content_for :header do %>
  <h1>New Item</h1>
<% end %>

<% content_for :content do %>
  <%= render partial: 'form' %>
<% end %>

app/views/inventory_items/show.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Inventory', project_inventory_path(@project) %></li>
  <li><%= link_to 'Items', project_inventory_items_path(@project) %></li>
  <li><%= @item.slug %></li>
<% end %>

<% content_for :header do %>
  <h1><%= @item.slug %></h1>
  <%= link_to 'Edit', edit_project_inventory_item_path(@project, @item) %>
<% end %>

<% content_for :content do %>
  <ul>
    <li><%= @item.name %></li>
    <li><%= @item.slug %></li>
  </ul>
  <p><%= link_to "Manage behaviors (#{ @item.behaviors.count })", behavioral_api(@item) %></p>
<% end %>