config/routes.rb
Lassie::Application.routes.draw do

  # Root:
  root 'projects#index'

  # Login / Logout:
  get '/login' => 'sessions#new', as: 'signin'
  delete '/logout' => 'sessions#destroy', as: 'signout'

  # Sessions / Users / Behaviors
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  
  # Project resources:
  resources :projects do
    resources :actors
    resources :assets
    resources :behavior_types
    resources :inventory_combos
    resources :inventory_items
    resources :inventory_lists
    resources :scenes

    # Landing pages:
    get '/setup' => 'projects#setup'
    get '/inventory' => 'projects#inventory'
  end

  # JSON API methods
  resources :behaviors, except: [:new, :edit]
  resources :scene_layers, except: [:new, :edit]
  resources :scene_grids, except: [:new, :edit]
  resources :scene_matrices, except: [:new, :edit]

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_and_belongs_to_many :users
  
  has_many :actors, dependent: :destroy
  has_many :assets, dependent: :destroy
  has_many :behavior_types, dependent: :destroy
  has_many :inventory_combos, dependent: :destroy
  has_many :inventory_items, dependent: :destroy
  has_many :inventory_lists, dependent: :destroy
  has_many :scenes, dependent: :destroy

  after_create do
    self.behavior_types.create(slug: 'generic')
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout :select_layout
  
  before_action :require_signin
  before_action :find_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)
    redirect_to @project
  end

  def show
  end

  def edit
  end

  def update
    @project.update(project_params)
    redirect_to @project
  end

  def destroy
    @project.destroy
    redirect_to @project
  end

  def setup
    find_parent_project
  end

  def inventory
    find_parent_project
  end

  private

  def select_layout
    %(index new).include?(action_name) ? 'root' : 'project'
  end

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, user_ids: [])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  
  def find_parent_project
    @project = Project.find(params[:project_id])
  end

end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <h2>Collaborators</h2>
  <ul>
  <%= f.collection_check_boxes :user_ids, User.all, :id, :name do |b| %>
    <li><%= b.check_box %> <%= b.label %></li>
  <% end %>
  </ul>

  <%= f.submit "Submit" %>
  <%= link_to 'Cancel', cancel_path %>
<% end %>

app/views/projects/edit.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Projects', projects_path %></li>
  <li>Edit <%= @project.name %></li>
<% end %>

<% content_for :header do %>
  <h1>Edit <%= @project.name %></h1>
<% end %>

<% content_for :content do %>
  <%= render partial: 'form', locals: { cancel_path: @project } %>
<% end %>

app/views/projects/index.html.erb
<% content_for :breadcrumbs do %>
  <li>Projects</li>
<% end %>

<% content_for :header do %>
  <h1>Projects</h1>
  <%= link_to "+", new_project_path if admin_user? %>
<% end %>

<% content_for :content do %>
  <ul>
    <% @projects.each do |project| %>
      <% if admin_user? || project.users.include?(current_user) %>
      <li>
        <%= link_to project.name, project %>
        <% if admin_user? %>
          <%= link_to 'Edit', edit_project_path(project) %>
          <%= link_to 'Delete', project, method: 'delete' %>
        <% end %>
      </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/projects/inventory.html.erb
<% content_for :breadcrumbs do %>
  <li>Inventory</li>
<% end %>

<% content_for :header do %>
  <h1>Inventory</h1>
<% end %>

<% content_for :content do %>
  <ul>
    <li><%= link_to 'Lists', project_inventory_lists_path(@project) %></li>
    <li><%= link_to 'Items', project_inventory_items_path(@project) %></li>
    <li><%= link_to 'Combos', project_inventory_combos_path(@project) %></li>
  </ul>
<% end %>

app/views/projects/new.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Projects', projects_path %></li>
  <li>New Project</li>
<% end %>

<% content_for :header do %>
  <h1>New Project</h1>
<% end %>

<% content_for :content do %>
  <%= render partial: 'form', locals: { cancel_path: projects_path } %>
<% end %>

app/views/projects/setup.html.erb
<% content_for :breadcrumbs do %>
  <li>Project Setup</li>
<% end %>

<% content_for :header do %>
  <h1>Project Setup</h1>
<% end %>

<% content_for :content do %>
  <ul>
    <li><%= link_to 'Behavior Types', project_behavior_types_path(@project) %></li>
    <li><%= link_to 'Actors', project_actors_path(@project) %></li>
  </ul>
<% end %>

app/views/projects/show.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Projects', projects_path %></li>
  <li><%= @project.name %></li>
<% end %>

<% content_for :header do %>
  <h1><%= @project.name %></h1>
  <%= link_to 'Edit', edit_project_path(@project) if admin_user? %>
<% end %>

<% content_for :content do %>
  <h2>Collaborators</h2>
  <ul>
    <% @project.users.each do |user| %>
    <li><%= content_tag :b, user.name %> (<%= user.email %>)</li>
    <% end %>
  </ul>
<% end %>