config/routes.rb
Lassie::Application.routes.draw do

  # Root:
  root 'projects#index'

  # Login / Logout:
  get '/login' => 'sessions#new', as: 'signin'
  delete '/logout' => 'sessions#destroy', as: 'signout'

  # Sessions / Users / Behaviors
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  
  # Project resources:
  resources :projects do
    resources :actors
    resources :assets
    resources :behavior_types
    resources :inventory_combos
    resources :inventory_items
    resources :inventory_lists
    resources :scenes

    # Landing pages:
    get '/setup' => 'projects#setup'
    get '/inventory' => 'projects#inventory'
  end

  # JSON API methods
  resources :behaviors, except: [:new, :edit]
  resources :scene_layers, except: [:new, :edit]
  resources :scene_grids, except: [:new, :edit]
  resources :scene_matrices, except: [:new, :edit]

end

app/models/inventory_list.rb
class InventoryList < ActiveRecord::Base
  belongs_to :project
  has_and_belongs_to_many :inventory_items
end

app/controllers/inventory_lists_controller.rb
class InventoryListsController < ApplicationController
  layout 'project'

  before_action :require_signin
  before_action :find_parent_project
  before_action :find_inventory_list, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
    @list = InventoryList.new
  end

  def create
    @project.inventory_lists.create(inventory_list_params)
    redirect_to project_inventory_lists_path(@project)
  end

  def show
  end

  def edit
  end

  def update
    @list.update(inventory_list_params)
    redirect_to project_inventory_lists_path(@project)
  end

  def destroy
  end

  private

  def find_inventory_list
    @list = InventoryList.find(params[:id])
  end

  def inventory_list_params
    params.require(:inventory_list).permit(:name, :slug, inventory_item_ids: [])
  end
end

app/views/inventory_lists/_form.html.erb
<%= form_for [@project, @list] do |f| %>
<ul>
  <li>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </li>
  <li>
  <%= f.label :slug %>
  <%= f.text_field :slug %>
  </li>
</ul>

<h2>Contents</h2>
<ul>
<%= f.collection_check_boxes :inventory_item_ids, InventoryItem.all, :id, :slug do |b| %>
  <li><%= b.check_box %> <%= b.label %></li>
<% end %>
</ul>

<%= f.submit 'Submit', id: 'submit' %>
<%= link_to 'Cancel', project_inventory_lists_path(@project) %>
<% end %>

app/views/inventory_lists/edit.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Inventory', project_inventory_path(@project) %></li>
  <li><%= link_to 'Lists', project_inventory_lists_path(@project) %></li>
  <li>Edit <%= @list.slug %></li>
<% end %>

<% content_for :header do %>
  <h1>Edit <%= @list.slug %></h1>
<% end %>

<% content_for :content do %>
  <%= render partial: 'form' %>
<% end %>

app/views/inventory_lists/index.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Inventory', project_inventory_path(@project) %></li>
  <li>Lists</li>
<% end %>

<% content_for :header do %>
  <h1>Inventory Lists</h1>
  <%= link_to '+', new_project_inventory_list_path(@project) %>
<% end %>

<% content_for :content do %>
  <ul>
    <% @project.inventory_lists.each do |list| %>
    <li>
      <%= link_to list.slug, project_inventory_list_path(@project, list) %>
      <%= link_to 'Edit', edit_project_inventory_list_path(@project, list) %>
      <%= link_to 'Delete', project_inventory_list_path(@project, list), method: 'delete' %>
    </li>
    <% end %>
  </ul>
<% end %>

app/views/inventory_lists/new.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Inventory', project_inventory_path(@project) %></li>
  <li><%= link_to 'Lists', project_inventory_lists_path(@project) %></li>
  <li>New List</li>
<% end %>

<% content_for :header do %>
  <h1>New List</h1>
<% end %>

<% content_for :content do %>
  <%= render partial: 'form' %>
<% end %>

app/views/inventory_lists/show.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Inventory', project_inventory_path(@project) %></li>
  <li><%= link_to 'Lists', project_inventory_lists_path(@project) %></li>
  <li><%= @list.slug %></li>
<% end %>

<% content_for :header do %>
  <h1>Inventory List: <%= @list.slug %></h1>
  <%= link_to 'Edit', edit_project_inventory_list_path(@project, @list) %>
<% end %>

<% content_for :content do %>
  <ul>
    <li><%= @list.slug %></li>
  </ul>

  <h2>Items</h2>
  <ul>
    <% @list.inventory_items.each do |item| %>
      <li><%= content_tag :b, item.slug %></li>
    <% end %>
  </ul>
<% end %>