config/routes.rb
Lassie::Application.routes.draw do

  # Root:
  root 'projects#index'

  # Login / Logout:
  get '/login' => 'sessions#new', as: 'signin'
  delete '/logout' => 'sessions#destroy', as: 'signout'

  # Sessions / Users / Behaviors
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  
  # Project resources:
  resources :projects do
    resources :actors
    resources :assets
    resources :behavior_types
    resources :inventory_combos
    resources :inventory_items
    resources :inventory_lists
    resources :scenes

    # Landing pages:
    get '/setup' => 'projects#setup'
    get '/inventory' => 'projects#inventory'
  end

  # JSON API methods
  resources :behaviors, except: [:new, :edit]
  resources :scene_layers, except: [:new, :edit]
  resources :scene_grids, except: [:new, :edit]
  resources :scene_matrices, except: [:new, :edit]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Lassie</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= yield(:body_class) if content_for?(:body_class) %>">

  <div class="navbar">
    <% if signed_in? %>
    <ul id="user-menu" class="user-menu">
      <li>Welcome <%= link_to current_user.name, current_user %></li>
      <li>
        <%= form_for :session, url: signout_path, method: 'delete' do |f| %>
          <%= f.submit 'Sign out', id: 'signout' %>
        <% end %>
      </li>
    </ul>
    <% end %>

    <% if content_for?(:navbar) %>
    <ul id="app-menu" class="app-menu" role="navigation">
      <%= yield(:navbar) %>
    </ul>
    <% end %>
  </div>

  <%= yield(:main) if content_for?(:main) %>
  <%= yield %>
  
</body>
</html>

app/views/layouts/editor.html.erb
<% content_for :main do %>
<div class="main" role="main">
  <% if content_for?(:breadcrumbs) %>
  <ul class="breadcrumbs"><%= yield(:breadcrumbs) %></ul>
  <% end %>

  <% if content_for?(:header) %>
  <div class="header"><%= yield(:header) %></div>
  <% end %>
  
  <div class="content">
    <% if flash.any? %>
    <ul class="flash">
      <% flash.each do |name, msg| %>
      <%= content_tag :li, msg, class: name %>
      <% end %>
    </ul>
    <% end %>

    <%= yield(:content) if content_for?(:content) %>
  </div>
</div>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/project.html.erb
<% content_for :navbar do %>
  <li class="back"><%= link_to 'Projects', projects_path %></li>
  <li>
    <%= link_to 'Setup', project_setup_path(@project), class: navbar_active_list(%(setup actors behavior_types)) %>
    <ul>
      <li><%= link_to 'Behavior Types', project_behavior_types_path(@project), class: navbar_active('behavior_types') %></li>
      <li><%= link_to 'Actors', project_actors_path(@project), class: navbar_active('actors') %></li>
    </ul>
  </li>
  <li>
    <%= link_to 'Inventory', project_inventory_path(@project), class: navbar_active_list(%(inventory inventory_lists inventory_items inventory_combos)) %>
    <ul>
      <li><%= link_to 'Lists', project_inventory_lists_path(@project), class: navbar_active('inventory_lists') %></li>
      <li><%= link_to 'Items', project_inventory_items_path(@project), class: navbar_active('inventory_items') %></li>
      <li><%= link_to 'Combos', project_inventory_combos_path(@project), class: navbar_active('inventory_combos') %></li>
    </ul>
  </li>
  <li><%= link_to 'Scenes', project_scenes_path(@project), class: navbar_active('scenes') %></li>
  <li><%= link_to 'Assets', project_assets_path(@project), class: navbar_active('assets') %></li>
<% end %>

<%= render template: "layouts/editor" %>

app/views/layouts/root.html.erb
<% content_for :navbar do %>
  <li><%= link_to 'Projects', projects_path, class: navbar_active('projects') %></li>
  <li><%= link_to 'Authors', users_path, class: navbar_active('users') %></li>
<% end %>

<%= render template: "layouts/editor" %>